on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Launch Runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get GitHub Runner Registration Token
      run: |
        TOKEN=$(curl -X POST \
                     -H "Authorization: token ${{ secrets.GITHUB_PAT }}" \
                     -H "Accept: application/vnd.github.v3+json" \
                     https://api.github.com/repos/alfredodeza/azure-spot-runner/actions/runners/registration-token | grep token | cut -d '"' -f 4)
        echo "TOKEN=$TOKEN" >> $GITHUB_ENV
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    - name: Modify cloud-init.txt
      run: |
        sed -i "2iTOKEN=$TOKEN" workflow-artifacts/cloud-init.txt

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Find the latest image URI
      id: find_image
      uses: azure/CLI@v1
      with:
        inlineScript: |
          IMAGE_URI=$(az image list --resource-group github-vms --query "[-1].id" --output tsv)
          echo "::set-output name=image_uri::$IMAGE_URI"


    - name: CREATE VM
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az vm create --resource-group github-vms  --name "app-vm-${{ GITHUB.RUN_NUMBER }}"  --admin-username "runner" --admin-password "${{ secrets.VM_PASSWORD }}" --location  eastus \
          --custom-data workflow-artifacts/cloud-init.txt \
          --image "${{ steps.find_image.outputs.image_uri }}"
